// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chapter.sql

package database

import (
	"context"
	"database/sql"
)

const getChapter = `-- name: GetChapter :one
SELECT id, manga_id, title, number, volume, source_id, url, status, file_path, file_size, page_count, is_read, current_page, read_at, published_at, downloaded_at, created_at FROM chapter WHERE id = ? LIMIT 1
`

func (q *Queries) GetChapter(ctx context.Context, id int64) (*Chapter, error) {
	row := q.db.QueryRowContext(ctx, getChapter, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.MangaID,
		&i.Title,
		&i.Number,
		&i.Volume,
		&i.SourceID,
		&i.Url,
		&i.Status,
		&i.FilePath,
		&i.FileSize,
		&i.PageCount,
		&i.IsRead,
		&i.CurrentPage,
		&i.ReadAt,
		&i.PublishedAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const insertChapter = `-- name: InsertChapter :one
INSERT INTO chapter (
    manga_id, title, number, volume, source_id, url, published_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (manga_id, source_id) DO UPDATE SET
    title = excluded.title,
    number = excluded.number,
    volume = excluded.volume,
    url = excluded.url
RETURNING id, manga_id, title, number, volume, source_id, url, status, file_path, file_size, page_count, is_read, current_page, read_at, published_at, downloaded_at, created_at
`

type InsertChapterParams struct {
	MangaID     int64          `json:"manga_id"`
	Title       string         `json:"title"`
	Number      float64        `json:"number"`
	Volume      sql.NullString `json:"volume"`
	SourceID    string         `json:"source_id"`
	Url         string         `json:"url"`
	PublishedAt sql.NullString `json:"published_at"`
}

func (q *Queries) InsertChapter(ctx context.Context, arg InsertChapterParams) (*Chapter, error) {
	row := q.db.QueryRowContext(ctx, insertChapter,
		arg.MangaID,
		arg.Title,
		arg.Number,
		arg.Volume,
		arg.SourceID,
		arg.Url,
		arg.PublishedAt,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.MangaID,
		&i.Title,
		&i.Number,
		&i.Volume,
		&i.SourceID,
		&i.Url,
		&i.Status,
		&i.FilePath,
		&i.FileSize,
		&i.PageCount,
		&i.IsRead,
		&i.CurrentPage,
		&i.ReadAt,
		&i.PublishedAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listChaptersByManga = `-- name: ListChaptersByManga :many
SELECT id, manga_id, title, number, volume, source_id, url, status, file_path, file_size, page_count, is_read, current_page, read_at, published_at, downloaded_at, created_at FROM chapter WHERE manga_id = ? ORDER BY number DESC
`

func (q *Queries) ListChaptersByManga(ctx context.Context, mangaID int64) ([]*Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByManga, mangaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.MangaID,
			&i.Title,
			&i.Number,
			&i.Volume,
			&i.SourceID,
			&i.Url,
			&i.Status,
			&i.FilePath,
			&i.FileSize,
			&i.PageCount,
			&i.IsRead,
			&i.CurrentPage,
			&i.ReadAt,
			&i.PublishedAt,
			&i.DownloadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChapterRead = `-- name: MarkChapterRead :exec
UPDATE chapter SET is_read = 1, read_at = datetime('now') WHERE id = ?
`

func (q *Queries) MarkChapterRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markChapterRead, id)
	return err
}

const updateChapterStatus = `-- name: UpdateChapterStatus :one
UPDATE chapter SET
    status = ?,
    file_path = ?,
    file_size = ?,
    page_count = ?,
    downloaded_at = CASE WHEN ? = 'completed' THEN datetime('now') ELSE downloaded_at END
WHERE id = ?
RETURNING id, manga_id, title, number, volume, source_id, url, status, file_path, file_size, page_count, is_read, current_page, read_at, published_at, downloaded_at, created_at
`

type UpdateChapterStatusParams struct {
	Status    sql.NullString `json:"status"`
	FilePath  sql.NullString `json:"file_path"`
	FileSize  sql.NullInt64  `json:"file_size"`
	PageCount sql.NullInt64  `json:"page_count"`
	Column5   interface{}    `json:"column_5"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateChapterStatus(ctx context.Context, arg UpdateChapterStatusParams) (*Chapter, error) {
	row := q.db.QueryRowContext(ctx, updateChapterStatus,
		arg.Status,
		arg.FilePath,
		arg.FileSize,
		arg.PageCount,
		arg.Column5,
		arg.ID,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.MangaID,
		&i.Title,
		&i.Number,
		&i.Volume,
		&i.SourceID,
		&i.Url,
		&i.Status,
		&i.FilePath,
		&i.FileSize,
		&i.PageCount,
		&i.IsRead,
		&i.CurrentPage,
		&i.ReadAt,
		&i.PublishedAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const updateReadingProgress = `-- name: UpdateReadingProgress :exec
UPDATE chapter SET current_page = ? WHERE id = ?
`

type UpdateReadingProgressParams struct {
	CurrentPage sql.NullInt64 `json:"current_page"`
	ID          int64         `json:"id"`
}

func (q *Queries) UpdateReadingProgress(ctx context.Context, arg UpdateReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateReadingProgress, arg.CurrentPage, arg.ID)
	return err
}
