// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: download_queue.sql

package database

import (
	"context"
	"database/sql"
)

const deleteDownload = `-- name: DeleteDownload :exec
DELETE FROM download_queue WHERE id = ?
`

func (q *Queries) DeleteDownload(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDownload, id)
	return err
}

const enqueueDownload = `-- name: EnqueueDownload :one
INSERT INTO download_queue (
    chapter_id, priority
) VALUES (?, ?)
ON CONFLICT (chapter_id) DO UPDATE SET
    priority = excluded.priority,
    status = 'queued',
    attempts = 0,
    last_error = NULL,
    started_at = NULL,
    completed_at = NULL
RETURNING id, chapter_id, priority, attempts, max_attempts, last_error, status, created_at, started_at, completed_at
`

type EnqueueDownloadParams struct {
	ChapterID int64         `json:"chapter_id"`
	Priority  sql.NullInt64 `json:"priority"`
}

func (q *Queries) EnqueueDownload(ctx context.Context, arg EnqueueDownloadParams) (*DownloadQueue, error) {
	row := q.db.QueryRowContext(ctx, enqueueDownload, arg.ChapterID, arg.Priority)
	var i DownloadQueue
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const listQueue = `-- name: ListQueue :many
SELECT id, chapter_id, priority, attempts, max_attempts, last_error, status, created_at, started_at, completed_at FROM download_queue
ORDER BY priority DESC, created_at ASC
`

func (q *Queries) ListQueue(ctx context.Context) ([]*DownloadQueue, error) {
	rows, err := q.db.QueryContext(ctx, listQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DownloadQueue{}
	for rows.Next() {
		var i DownloadQueue
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Priority,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadStatus = `-- name: UpdateDownloadStatus :one
UPDATE download_queue SET
    status = ?,
    attempts = ?,
    last_error = ?,
    started_at = ?,
    completed_at = ?
WHERE id = ?
RETURNING id, chapter_id, priority, attempts, max_attempts, last_error, status, created_at, started_at, completed_at
`

type UpdateDownloadStatusParams struct {
	Status      sql.NullString `json:"status"`
	Attempts    sql.NullInt64  `json:"attempts"`
	LastError   sql.NullString `json:"last_error"`
	StartedAt   sql.NullString `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) (*DownloadQueue, error) {
	row := q.db.QueryRowContext(ctx, updateDownloadStatus,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i DownloadQueue
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return &i, err
}
