// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Chapter struct {
	ID           int64          `json:"id"`
	MangaID      int64          `json:"manga_id"`
	Title        string         `json:"title"`
	Number       float64        `json:"number"`
	Volume       sql.NullString `json:"volume"`
	SourceID     string         `json:"source_id"`
	Url          string         `json:"url"`
	Status       sql.NullString `json:"status"`
	FilePath     sql.NullString `json:"file_path"`
	FileSize     sql.NullInt64  `json:"file_size"`
	PageCount    sql.NullInt64  `json:"page_count"`
	IsRead       sql.NullInt64  `json:"is_read"`
	CurrentPage  sql.NullInt64  `json:"current_page"`
	ReadAt       sql.NullString `json:"read_at"`
	PublishedAt  sql.NullString `json:"published_at"`
	DownloadedAt sql.NullString `json:"downloaded_at"`
	CreatedAt    sql.NullString `json:"created_at"`
}

type DownloadQueue struct {
	ID          int64          `json:"id"`
	ChapterID   int64          `json:"chapter_id"`
	Priority    sql.NullInt64  `json:"priority"`
	Attempts    sql.NullInt64  `json:"attempts"`
	MaxAttempts sql.NullInt64  `json:"max_attempts"`
	LastError   sql.NullString `json:"last_error"`
	Status      sql.NullString `json:"status"`
	CreatedAt   sql.NullString `json:"created_at"`
	StartedAt   sql.NullString `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
}

type Manga struct {
	ID             int64          `json:"id"`
	Title          string         `json:"title"`
	Slug           string         `json:"slug"`
	Source         string         `json:"source"`
	SourceID       string         `json:"source_id"`
	Url            string         `json:"url"`
	CoverUrl       sql.NullString `json:"cover_url"`
	CoverPath      sql.NullString `json:"cover_path"`
	Description    sql.NullString `json:"description"`
	Status         sql.NullString `json:"status"`
	Author         sql.NullString `json:"author"`
	Artist         sql.NullString `json:"artist"`
	Genres         sql.NullString `json:"genres"`
	Tags           sql.NullString `json:"tags"`
	AnilistID      sql.NullInt64  `json:"anilist_id"`
	MalID          sql.NullInt64  `json:"mal_id"`
	UpdateInterval sql.NullString `json:"update_interval"`
	AutoDownload   sql.NullInt64  `json:"auto_download"`
	CreatedAt      sql.NullString `json:"created_at"`
	UpdatedAt      sql.NullString `json:"updated_at"`
	LastCheckedAt  sql.NullString `json:"last_checked_at"`
}

type Scraper struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Path      sql.NullString `json:"path"`
	Enabled   sql.NullInt64  `json:"enabled"`
	Config    sql.NullString `json:"config"`
	CreatedAt sql.NullString `json:"created_at"`
	UpdatedAt sql.NullString `json:"updated_at"`
}

type Setting struct {
	Key       string         `json:"key"`
	Value     string         `json:"value"`
	UpdatedAt sql.NullString `json:"updated_at"`
}
